"""empty message

Revision ID: 807beb196275
Revises: 077635c95cba
Create Date: 2025-02-17 01:15:36.189219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807beb196275'
down_revision = '077635c95cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['Sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Players')
    # ### end Alembic commands ###
