x-common-build: &app-build
  build:
    context: ..
    dockerfile: /docker/Dockerfile
  image: flask_app:latest
  volumes:
    - ../app:/app
  environment:
    - REDIS_URL=redis://redis:6379/0
    - DOCKER_CONTAINER=true

services:
  web:
    <<: *app-build
    entrypoint: ["python", "app.py"]
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - redis

  celery:
    <<: *app-build
    container_name: celery_worker
    entrypoint: ["celery" ,"-A", "celery_worker.celery", "worker", "--loglevel=info"]
    depends_on:
      - web
      - redis
    
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"