"""empty message

Revision ID: 017829ce6066
Revises: 13e30515c19f
Create Date: 2025-05-20 20:53:47.854775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '017829ce6066'
down_revision = '13e30515c19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.alter_column('base_rule_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('nmpz')
        batch_op.drop_column('time_limit')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('base_rule_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('sessions_ibfk_2', type_='foreignkey')
        batch_op.drop_column('map_id')
        batch_op.drop_column('max_rounds')
        batch_op.drop_column('nmpz')
        batch_op.drop_column('time_limit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nmpz', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('max_rounds', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('map_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('sessions_ibfk_2', 'maps', ['map_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('base_rule_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nmpz', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.alter_column('base_rule_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
