"""empty message

Revision ID: 027b2bb4c260
Revises: 141e07957994
Create Date: 2025-02-19 21:23:34.148281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027b2bb4c260'
down_revision = '141e07957994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('CHALLENGE', name='gametype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
