"""empty message

Revision ID: 19251cb3cd5c
Revises: 7d2960d6eda5
Create Date: 2025-05-13 17:34:51.347619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19251cb3cd5c'
down_revision = '7d2960d6eda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_colors')
    with op.batch_alter_table('cosmetics_ownership', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cosmetics', ['cosmetics_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('usermapstats', schema=None) as batch_op:
        batch_op.alter_column('nmpz',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermapstats', schema=None) as batch_op:
        batch_op.alter_column('nmpz',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    with op.batch_alter_table('cosmetics_ownership', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('user_colors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hue', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('saturation', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brightness', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_colors_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
