"""empty message

Revision ID: 1b9ca4869fa7
Revises: 8cbfbea025b3
Create Date: 2025-05-14 16:02:53.487497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9ca4869fa7'
down_revision = '8cbfbea025b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cosmetics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('body_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hat_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cosmetics', ['hat_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'cosmetics', ['body_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'cosmetics', ['face_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cosmetics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hat_id')
        batch_op.drop_column('body_id')
        batch_op.drop_column('face_id')

    # ### end Alembic commands ###
