"""empty message

Revision ID: 255734513858
Revises: eadf475001cf
Create Date: 2025-03-26 20:58:02.089663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255734513858'
down_revision = 'eadf475001cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NMPZ', sa.Boolean(), default=False))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NMPZ', sa.Boolean(), default=False))

    with op.batch_alter_table('usermapstats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NMPZ', sa.Boolean(), default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermapstats', schema=None) as batch_op:
        batch_op.drop_column('NMPZ')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('NMPZ')

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_column('NMPZ')

    # ### end Alembic commands ###
