"""empty message

Revision ID: 28f566078d91
Revises: 7672c22b5ed7
Create Date: 2025-03-03 22:26:11.245741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f566078d91'
down_revision = '7672c22b5ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guesses', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
