"""empty message

Revision ID: 2e06978dd636
Revises: dce099f8142e
Create Date: 2025-03-14 16:03:47.843744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e06978dd636'
down_revision = 'dce099f8142e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bounds', schema=None) as batch_op:
        batch_op.alter_column('start_latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('start_longitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('end_latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('end_longitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Double(),
               existing_nullable=False)

    with op.batch_alter_table('guesses', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('distance',
               existing_type=mysql.DECIMAL(precision=10, scale=3),
               type_=sa.Double(),
               existing_nullable=False)

    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.alter_column('start_latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('start_longitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('end_latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('end_longitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('max_distance',
               existing_type=mysql.DECIMAL(precision=10, scale=3),
               type_=sa.Double(),
               existing_nullable=False)

    with op.batch_alter_table('mapstats', schema=None) as batch_op:
        batch_op.alter_column('total_distance',
               existing_type=mysql.DECIMAL(precision=12, scale=3),
               type_=sa.Double(),
               existing_nullable=False)

    with op.batch_alter_table('roundstats', schema=None) as batch_op:
        batch_op.alter_column('total_distance',
               existing_type=mysql.DECIMAL(precision=12, scale=3),
               type_=sa.Double(),
               existing_nullable=False)

    with op.batch_alter_table('svlocations', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Double(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('svlocations', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=False)

    with op.batch_alter_table('roundstats', schema=None) as batch_op:
        batch_op.alter_column('total_distance',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=12, scale=3),
               existing_nullable=False)

    with op.batch_alter_table('mapstats', schema=None) as batch_op:
        batch_op.alter_column('total_distance',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=12, scale=3),
               existing_nullable=False)

    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.alter_column('max_distance',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=10, scale=3),
               existing_nullable=False)
        batch_op.alter_column('end_longitude',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=False)
        batch_op.alter_column('end_latitude',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=False)
        batch_op.alter_column('start_longitude',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=False)
        batch_op.alter_column('start_latitude',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=False)

    with op.batch_alter_table('guesses', schema=None) as batch_op:
        batch_op.alter_column('distance',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=10, scale=3),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=False)

    with op.batch_alter_table('bounds', schema=None) as batch_op:
        batch_op.alter_column('end_longitude',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=False)
        batch_op.alter_column('end_latitude',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=False)
        batch_op.alter_column('start_longitude',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=False)
        batch_op.alter_column('start_latitude',
               existing_type=sa.Double(),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=False)

    # ### end Alembic commands ###
