"""empty message

Revision ID: 3d0b671f8235
Revises: ee9110029806
Create Date: 2025-05-12 14:27:52.298453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d0b671f8235'
down_revision = 'ee9110029806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('globals')
    op.drop_table('usercosmetics')

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.alter_column('nmpz',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('nmpz',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    with op.batch_alter_table('user_cosmetics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('body', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('hat', sa.String(length=50), nullable=False))

    with op.batch_alter_table('usermapstats', schema=None) as batch_op:
        batch_op.alter_column('nmpz',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermapstats', schema=None) as batch_op:
        batch_op.alter_column('nmpz',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    with op.batch_alter_table('user_cosmetics', schema=None) as batch_op:
        batch_op.drop_column('hat')
        batch_op.drop_column('body')
        batch_op.drop_column('face')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('nmpz',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.alter_column('nmpz',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    with op.batch_alter_table('cosmetics', schema=None) as batch_op:
        batch_op.drop_column('type')

    op.create_table('face_cosmetics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('tier', mysql.ENUM('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('face_cosmetics', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('body_cosmetics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('tier', mysql.ENUM('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('body_cosmetics', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('usercosmetics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('map_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', mysql.VARCHAR(length=7), nullable=False),
    sa.Column('icon', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('size', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], name='usercosmetics_ibfk_3'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='usercosmetics_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='usercosmetics_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('globals',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('GoogleMiniMapCalls', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('GoogleMiniMapLimit', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
