"""empty message

Revision ID: 5a7881f6ce16
Revises: 6f0af4a38022
Create Date: 2025-05-15 13:12:42.287346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a7881f6ce16'
down_revision = '6f0af4a38022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_challenge', schema=None) as batch_op:
        batch_op.alter_column('coins_added',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_challenge', schema=None) as batch_op:
        batch_op.alter_column('coins_added',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
