"""empty message

Revision ID: 6f0af4a38022
Revises: 
Create Date: 2025-05-15 13:03:57.551180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0af4a38022'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins_added', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_challenge', schema=None) as batch_op:
        batch_op.drop_column('coins_added')

    # ### end Alembic commands ###
