"""empty message

Revision ID: 74979c261c56
Revises: 75cff7aefe49
Create Date: 2025-04-16 19:26:43.064953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74979c261c56'
down_revision = '75cff7aefe49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapstats', schema=None) as batch_op:
        batch_op.drop_column('total_generation_time')
        batch_op.drop_column('total_loads')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapstats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_loads', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_generation_time', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
