"""empty message

Revision ID: 75cff7aefe49
Revises: 24723103c9d0
Create Date: 2025-04-08 18:40:56.991306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75cff7aefe49'
down_revision = '24723103c9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermapstats', schema=None) as batch_op:
        dialect = op.get_bind().dialect.name
        if dialect == 'mysql':
            batch_op.drop_constraint('usermapstats_ibfk_3', type_='foreignkey')
        elif dialect == 'postgresql':
            batch_op.drop_constraint('usermapstats_high_session_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sessions', ['high_session_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermapstats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('usermapstats_ibfk_3', 'sessions', ['high_session_id'], ['id'])

    # ### end Alembic commands ###
