"""empty message

Revision ID: 7672c22b5ed7
Revises: 027b2bb4c260
Create Date: 2025-02-21 13:38:49.395746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7672c22b5ed7'
down_revision = '027b2bb4c260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index('uuid')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', mysql.VARCHAR(length=36), nullable=True))
        batch_op.create_index('uuid', ['uuid'], unique=True)

    # ### end Alembic commands ###
