"""empty message

Revision ID: 7c892a5b524b
Revises: 4171b6e7e638
Create Date: 2025-03-15 19:26:04.955751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c892a5b524b'
down_revision = '4171b6e7e638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermapstats', schema=None) as batch_op:
        batch_op.alter_column('total_distance',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('high_average_distance',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermapstats', schema=None) as batch_op:
        batch_op.alter_column('high_average_distance',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('total_distance',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
