"""empty message

Revision ID: 7d2960d6eda5
Revises: 3d0b671f8235
Create Date: 2025-05-13 15:10:26.876633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d2960d6eda5'
down_revision = '3d0b671f8235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cosmetics_ownership', schema=None) as batch_op:
        batch_op.drop_constraint('cosmetics_ownership_ibfk_2', type_='foreignkey')

    # Now, drop the related tables
    op.drop_table('user_cosmetics')
    op.drop_table('cosmetics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cosmetics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('tier', mysql.ENUM('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY'), nullable=False),
    sa.Column('top', mysql.FLOAT(), nullable=False),
    sa.Column('left', mysql.FLOAT(), nullable=False),
    sa.Column('scale', mysql.FLOAT(), nullable=False),
    sa.Column('type', mysql.ENUM('FACE', 'BODY', 'HAT'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('cosmetics', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('user_cosmetics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hue', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('saturation', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brightness', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('face', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('body', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('hat', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_cosmetics_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
