"""empty message

Revision ID: 8cbfbea025b3
Revises: ee9110029806
Create Date: 2025-05-13 18:00:26.175559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbfbea025b3'
down_revision = 'ee9110029806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_lobby', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_members', schema=None) as batch_op:
        batch_op.drop_column('in_lobby')

    # ### end Alembic commands ###
