"""empty message

Revision ID: a81c771bdf07
Revises: 7c892a5b524b
Create Date: 2025-03-15 23:00:31.814032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81c771bdf07'
down_revision = '7c892a5b524b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermapstats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('high_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sessions', ['high_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usermapstats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('high_session_id')

    # ### end Alembic commands ###
