"""empty message

Revision ID: a8b90e4859ec
Revises: 377d4b7f36f4
Create Date: 2025-03-28 17:05:32.632891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b90e4859ec'
down_revision = '377d4b7f36f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
