"""empty message

Revision ID: bed275abd1fb
Revises: 19251cb3cd5c
Create Date: 2025-05-13 21:44:31.758726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bed275abd1fb'
down_revision = '19251cb3cd5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cosmetics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top_position', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('left_position', sa.Float(), nullable=False))
        batch_op.drop_column('top')
        batch_op.drop_column('left')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cosmetics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('left', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('top', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('left_position')
        batch_op.drop_column('top_position')

    # ### end Alembic commands ###
