"""empty message

Revision ID: c747b6d58acb
Revises: 74979c261c56
Create Date: 2025-04-20 20:06:41.404273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c747b6d58acb'
down_revision = '74979c261c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_challenge', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_challenge', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
