"""empty message

Revision ID: c91d34d78edb
Revises: 
Create Date: 2025-05-15 13:52:57.391048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91d34d78edb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_lobby', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_members', schema=None) as batch_op:
        batch_op.drop_column('in_lobby')

    # ### end Alembic commands ###
