"""empty message

Revision ID: ee9110029806
Revises: c747b6d58acb
Create Date: 2025-04-22 17:01:49.483379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9110029806'
down_revision = 'c747b6d58acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapeditors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission_level', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapeditors', schema=None) as batch_op:
        batch_op.drop_column('permission_level')

    # ### end Alembic commands ###
